# Site settings
title: TechnoBlog
description: TechnoBlog, 4 all technology
keywords: Technology, Blogging, Fun
author: Alex
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
